CREATE DATABASE employees_info;
CREATE DATABASE airpot_info;
USE employees_info;
CREATE TABLE employee_details(id bigint);
USE employees_info;
ALTER TABLE employee_details ADD column reg_no bigint;
ALTER TABLE employee_details ADD column address int;
ALTER TABLE employee_details ADD column phone_no varchar(25);
ALTER TABLE employee_details ADD column account_no varchar(20);
ALTER TABLE employee_details ADD column pan_no int;
USE airpot_info;
CREATE TABLE airport_details(passenger_name bigint);
ALTER TABLE airport_details ADD column travel_type int;
ALTER TABLE airport_details ADD column travel_fee varchar(30);
ALTER TABLE airport_details ADD column  sources int;
ALTER TABLE airport_details ADD column destitation bigint;
ALTER TABLE airport_details ADD column seat int;
USE employees_info;
ALTER TABLE employee_details RENAME COLUMN reg_no to register_no;
ALTER TABLE employee_details RENAME COLUMN phone_no to employee_phone_no;
ALTER TABLE employee_details RENAME COLUMN account_no to employee_account_no;
USE airpot_info;
ALTER TABLE airport_details DROP COLUMN travel_type;
USE employees_info;
ALTER TABLE employee_details DROP COLUMN pan_no;
ALTER TABLE employee_details MODIFY COLUMN address varchar(35);
ALTER TABLE employee_details MODIFY COLUMN employee_phone_no bigint;
USE airpot_info;
ALTER TABLE airport_details MODIFY COLUMN  travel_fee int;
ALTER TABLE airport_details MODIFY COLUMN sources varchar(20);
USE employees_info;
SELECT * FROM employee_details;
USE airpot_info;
DESC airport_details; 
ALTER TABLE airport_details MODIFY COLUMN passenger_name varchar(30);
ALTER TABLE airport_details MODIFY COLUMN destitation varchar(30);
USE airpot_info;
INSERT INTO airport_details values('Osama',5,'bangalore','delhi',5);
SELECT * FROM airport_details;
INSERT INTO airport_details values('Azees',3,'bangalore','HIMACHAL',3);
INSERT INTO airport_details values('Haseena',5,'chennai','bangalore',6);
INSERT INTO airport_details values('Assadiq',3,'bangalore','chennai',7);
INSERT INTO airport_details values('Mosina',4,'mysore','chennai',8);
INSERT INTO airport_details values('Mujahid',3,'coimbatore','chennai',9);
INSERT INTO airport_details values('Aswin',3,'madurai','bangalore',10);
INSERT INTO airport_details values('prem kumar',3,'salem','delhi',11);
INSERT INTO airport_details values('kalai',5,'bangalore','vijayawada',7);
INSERT INTO airport_details values('ranjith',3,'bangalore','hyderabad',7);